---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-secrets

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cloud-secrets
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cloud-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-secrets
subjects:
- kind: ServiceAccount
  name: cloud-secrets